config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :proofs
  resources :events
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/event.rb
class Event < ApplicationRecord
    enum :gender, [:female, :male, :mixed], _suffix: true, default: :female    
    enum :eventtype, [:qualify, :final], _suffix: true, default: :qualify

    def my_seed_time        
        #self.seed_time.strftime("%T.%L")
        return putTime(self.seed_time)
    end

    def my_event_time        
        #self.event_time.strftime("%T.%L")
        return putTime(self.event_time)
    end

    def putTime(my_time)
        #return my_time.strftime "%M:%S.%L"
        timeGap = my_time.seconds_since_midnight

        if timeGap < 1
            (my_time.strftime "0.%L").to_s
        elsif timeGap < 60
            (my_time.strftime "%S.%L").to_s
        elsif timeGap < 3600
            (my_time.strftime "%M:%S.%L").to_s
        else
            (my_time.strftime "%H:%M:%S.%L").to_s
        end
    end

    def my_gap
        timeGap = self.seed_time.minus_with_coercion(self.event_time)
        if timeGap.positive?
            preFix = "- " 
        else 
            timeGap *= -1
            preFix = "+ " 
        end

        if timeGap < 1
            preFix  + (Time.at(timeGap).utc.strftime "0.%L").to_s
        elsif timeGap < 60
            preFix + (Time.at(timeGap).utc.strftime "%s.%L").to_s
        elsif timeGap < 3600
            preFix + (Time.at(timeGap).utc.strftime "%M:%S.%L").to_s
        else
            preFix + (Time.at(timeGap).utc.strftime "%H:%M:%S.%L").to_s
        end
    end
end

app/models/proof.rb
class Proof < ApplicationRecord
    validates :abbreviation, :presence => true, uniqueness: true
    validates :description, :presence => true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
    before_action :set_proof, only: %i[new edit]
    before_action :set_event, only: %i[destroy]

    def index
        @events =  Event.all.order(:event_date)
    end

    def new 
        @event = Event.new
    end

    def create
        @event = Event.new(event_params) 

        if @event.save
            flash[:notice] = "Event successfully created"
            redirect_to events_path
        else
            message_str = "Event can't be created: "
            @event.errors.full_messages.each do |message|
                message_str += message + ". "
            end
            flash[:alert] =  message_str
            redirect_to new_event_path(@event)
        end      
    end

    def destroy
        if @event.destroy
            flash[:notice] = "Event successfully destroyed"
            redirect_to events_path
        else
            message_str = "Event can't be destroyed: "
            @event.errors.full_messages.each do |message|
                message_str += message + ". "
            end
            flash[:alert] =  message_str
            redirect_to events_path
        end      
    end

    def edit
        @event = Event.find params[:id]
    end

    def update
        @event = Event.find params[:id]
        if @event.update(event_params)
            flash[:notice] = "Event successfully updated" 
            redirect_to events_path
        else
            flash[:alert] = "Event can't be updated"
            redirect_to edit_event_path(@event)
        end
    end

    def show
        @event = Event.find(params[:id])
    end
    
    private
        def set_proof
            @proof = Proof.all.map {|proof| [proof.description.humanize, proof.abbreviation]}
        end

        def set_event
            @event = Event.find params[:id]
        end

        def event_params
            params.require(:event).permit(:id, :event_proof, :event_date, :event_gender, :event_type, :seed_time, :event_time)
        end


end

app/controllers/proofs_controller.rb
class ProofsController < ApplicationController
    before_action :set_proof, only: %i[destroy]

    def index
        @proofs = Proof.all
    end

    def show
        @proof = Proof.find(params[:id])
    end

    def edit
        @proof = Proof.find params[:id]
    end

    def update
        @proof = Proof.find params[:id]
        if @proof.update(proof_params)
            flash[:notice] = "Proof successfully updated" 
            redirect_to proofs_path
        else
            flash[:alert] = "Proof can't be updated"
            redirect_to edit_proof_path(@proof)
        end
    end

    def new 
        @proof = Proof.new
    end

    def create
        @proof = Proof.new(proof_params) 

        if @proof.save
            flash[:notice] = "Proof successfully created"
            redirect_to proofs_path
        else
            message_str = "Proof can't be created: "
            @proof.errors.full_messages.each do |message|
                message_str += message + ". "
            end
            flash[:alert] =  message_str
            redirect_to new_proof_path(@proof)
        end      
    end

    def destroy
        if @proof.destroy
            flash[:notice] = "Proof successfully destroyed"
            redirect_to proofs_path
        else
            message_str = "Proof can't be destroyed: "
            @proof.errors.full_messages.each do |message|
                message_str += message + ". "
            end
            flash[:alert] =  message_str
            redirect_to proofs_path
        end      
    end
    
    private 
    def proof_params
        params.require(:proof).permit(:abbreviation, :description, :id)
    end

    def set_proof
        @proof = Proof.find params[:id]
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/proofs_helper.rb
module ProofsHelper
end

app/views/events/_form.html.erb
<%= form_with(model: event, local: true) do |form| %>
    <% if event.errors.any? %>
        <div id="error_explanation">
            <h2><%= pluralize(event.errors.count, "error") %> 
                    prohibited this event from being saved:
            </h2>
            <ul>
                <% event.errors.full_messages.each do |message| %>
                    <li><%= message %></li>
                <% end %>
            </ul>
        </div>
    <% end %>

    <div class="field mt-3">
        <%= form.label :event_proof, class: "form-label text-capitalize" %>
        <%= form.select :event_proof, @proof, {}, class: "form-select" %>
    </div>

    <div class="field mt-1">
        <%= form.label :event_gender, class: "form-label text-capitalize" %>
        <%= form.select :event_gender, Event.genders.keys.map {|gen| [gen.humanize, gen]}, {}, class: "form-select" %>
    </div>

    <div class="field mt-1">
        <%= form.label :event_type, class: "form-label text-capitalize" %>
        <%= form.select :event_type, Event.eventtypes.keys.map {|type| [type.humanize, type]}, {}, class: "form-select" %>
    </div>

    <div class="field mt-1">
        <%= form.label :event_date, class: "form-label text-capitalize" %>
        <%= form.date_field :event_date, class: "form-control" %>
    </div>

    <div class="field mt-1">
        <%= form.label :seed_time, class: "form-label text-capitalize" %>
        <%= form.time_field :seed_time, {class: "form-control", step: "0.001"} %>
    </div>

    <div class="field mt-1">
        <%= form.label :event_time, class: "form-label text-capitalize" %>
        <%= form.time_field :event_time, {class: "form-control", step: "0.001"} %>
    </div>

    <div class="actions">
        <%= form.submit :Save, class: "btn btn-primary mt-3" %>
        <%= link_to 'Back', events_path(@event), class: "btn btn-primary mt-3" %>
    </div>

<% end %>

app/views/events/edit.html.erb
<header class="text-end">
    <h3>>> Edit a Event</h3>
</header>

<%= render 'form', event: @event %>

app/views/events/index.html.erb
<header class="text-end">
    <h3>
        >> Events <%= link_to icon('fa-solid', 'square-plus', class:'fa-1x'), new_event_path %>
    </h3>
</header>

<table class="table table-bordered text-center">
    <thead>
        <tr class="table-primary">
            <th>Date</th>
            <th>Proof</th>
            <th>Gender</th>
            <th>Event Type</th>
            <th>Seed Time</th>
            <th>Event Time</th>
            <th>Gap</th>
            <th colspan="3">Actions</th>
        </tr>
    </thead>
    <tbody>
        <% @events.each do |event| %>
            <tr>
                <td><%= event.event_date %></td>
                <td><%= event.event_proof %></td>
                <td class="text-capitalize"><%= event.event_gender %></td>
                <td class="text-capitalize"><%= event.event_type %></td>
                <td ><%= event.my_seed_time %></td>
                <td><%= event.my_event_time %></td>

                <% if event.my_gap[0] == "-"%>
                    <td class="text-success"><strong><%= event.my_gap %></strong></td>    
                <% else %>
                    <td class="text-danger"><strong><%= event.my_gap %></strong></td>    
                <% end %>
                
                <td><%= link_to icon('fa-solid', 'stopwatch'), event_path(event) %></td>
                <td><%= link_to icon('fa-solid', 'pencil'), edit_event_path(event) %></td>
                <td><%= link_to icon('fa-solid', 'trash'), event, method: :delete %></td>
            </tr>
        <% end %>
        <tr>
        <td colspan="10" class="text-start">
            <%= link_to icon('fa-solid', 'square-plus', class:'fa-1x'), new_event_path %> Add
        </td>
    </tbody>
</table>

app/views/events/new.html.erb
<header class="text-end">
    <h3>>> New Event</h3>
</header>

<%= render 'form', event: @event %>

app/views/events/show.html.erb
<header class="text-end">
    <h3>>>
        <%= @event.event_date %>
        /
        <%= @event.event_proof %>
        -
        <%= @event.event_type.capitalize%>
    </h3>
</header>
<p>
    <strong>Abbreviation:</strong>
    <%= @event.event_proof %>
</p>
<p>
    <strong>Description:</strong>
    <%#= @proof.description %>
</p>

<%#= link_to 'Edit', edit_proof_path(@proof)%> |
<%#= link_to 'Back', proofs_path(@proof) %>

app/views/layouts/_flash.html.erb
<svg xmlns="http://www.w3.org/2000/svg" style="display: none;">
    <symbol id="check-circle-fill" viewBox="0 0 16 16">
        <path fill="#0D6EFD" d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0zm-3.97-3.03a.75.75 0 0 0-1.08.022L7.477 9.417 5.384 7.323a.75.75 0 0 0-1.06 1.06L6.97 11.03a.75.75 0 0 0 1.079-.02l3.992-4.99a.75.75 0 0 0-.01-1.05z"/>
    </symbol>
    <symbol id="info-fill" viewBox="0 0 16 16">
        <path d="M8 16A8 8 0 1 0 8 0a8 8 0 0 0 0 16zm.93-9.412-1 4.705c-.07.34.029.533.304.533.194 0 .487-.07.686-.246l-.088.416c-.287.346-.92.598-1.465.598-.703 0-1.002-.422-.808-1.319l.738-3.468c.064-.293.006-.399-.287-.47l-.451-.081.082-.381 2.29-.287zM8 5.5a1 1 0 1 1 0-2 1 1 0 0 1 0 2z"/>
    </symbol>
    <symbol id="exclamation-triangle-fill" viewBox="0 0 16 16">
        <path fill="red" d="M8.982 1.566a1.13 1.13 0 0 0-1.96 0L.165 13.233c-.457.778.091 1.767.98 1.767h13.713c.889 0 1.438-.99.98-1.767L8.982 1.566zM8 5c.535 0 .954.462.9.995l-.35 3.507a.552.552 0 0 1-1.1 0L7.1 5.995A.905.905 0 0 1 8 5zm.002 6a1 1 0 1 1 0 2 1 1 0 0 1 0-2z"/>
    </symbol>
</svg>

<% if flash[:notice] %>
  <div class="alert alert-primary d-flex align-items-center mt-3" role="notice">
    <svg class="bi flex-shrink-0 me-2" role="img" aria-label="Notice:" width="32" height="32"><use xlink:href="#check-circle-fill"/></svg>
    <div>
      <h6><%= flash[:notice] %></h6>
    </div>
  </div>
<% end %>
<% if flash[:alert] %>
  <div class="alert alert-danger d-flex align-items-center mt-3" role="alert">
    <svg class="bi flex-shrink-0 me-2" role="img" aria-label="Alert:" width="32" height="32"><use xlink:href="#exclamation-triangle-fill"/></svg>
    <div>
      <h6><%= flash[:alert] %></h6>
    </div>
  </div>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-dark bg-primary">
    <div class="container-fluid">
        <a class="navbar-brand" href="#">Swimm;)rs</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarText">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="#">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Features</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Pricing</a>
                </li>
            </ul>
            <span class="navbar-text">
                Navbar text with an inline element
            </span>
        </div>
    </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Swimmers</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>    

    <div class="container mt-3">
      <%= render 'layouts/flash' %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/proofs/_form.html.erb
<%= form_with(model: proof, local: true) do |form| %>
    <% if proof.errors.any? %>
        <div id="error_explanation">
            <h2><%= pluralize(proof.errors.count, "error") %> 
                    prohibited this proof from being saved:
            </h2>
            <ul>
                <% proof.errors.full_messages.each do |message| %>
                    <li><%= message %></li>
                <% end %>
            </ul>
        </div>
    <% end %>

    <div class="field">
        <%= form.label :abbreviation, class: "form-label" %>
        <%= form.text_field :abbreviation, class: "form-control" %>
    </div>
    <div class="field mt-1">
        <%= form.label :description, class: "form-label" %>
        <%= form.text_field :description, class: "form-control" %>
    </div>
    <div class="actions">
        <%= form.submit :Save, class: "btn btn-primary mt-3" %>
        <%= link_to 'Back', proofs_path(@proof), class: "btn btn-primary mt-3" %>
    </div>

<% end %>

app/views/proofs/edit.html.erb
<h1>Editing A Proof</h1>

<%= render 'form', proof: @proof %>

<%= link_to 'Show', proof_path(@proof) %> |
<%= link_to 'Back', proofs_path(@proof) %>

app/views/proofs/index.html.erb
<header class="text-end">
    <h3>
        >> Proofs catalogue <%= link_to icon('fa-solid', 'square-plus', class:'fa-1x'), new_proof_path %>
    </h3>
</header>


<table class="table table-bordered">
    <thead>
        <tr class="table-primary">
            <th>Short Name</th>
            <th>Description</th>
            <th colspan="2" class="text-center">Actions</th>
        </tr>
    </thead>
    <tbody>
        <% @proofs.each do |proof| %>
            <tr>
                <td><%= proof.abbreviation %></td>
                <td><%= proof.description %></td>                
                <td class="text-center"><%= link_to icon('fa-solid', 'pencil'), edit_proof_path(proof) %></td>
                <td class="text-center"><%= link_to icon('fa-solid', 'trash'), proof, method: :delete %></td>
            </tr>
        <% end %>
        <tr>
        <td colspan="4" class="align-text-middle">
            <%= link_to icon('fa-solid', 'square-plus', class:'fa-1x'), new_proof_path %> Add
        </td>
    </tbody>
</table>

app/views/proofs/new.html.erb
<header class="text-end">
    <h3>>> New Proof</h3>
</header>

<%= render 'form', proof: @proof %>

app/views/proofs/show.html.erb
<h1>Proof Details</h1>
<p>
    <strong>Abbreviation:</strong>
    <%= @proof.abbreviation %>
</p>
<p>
    <strong>Description:</strong>
    <%= @proof.description %>
</p>
<p>
    <strong>Pool Type</strong>
    <%= @proof.pool_type %>
</p>
<%= link_to 'Edit', edit_proof_path(@proof)%> |
<%= link_to 'Back', proofs_path(@proof) %>

app/views/proofs/show_.html.erb
<h1>Proof Details</h1>
<p>
    <strong>Abbreviation:</strong>
    <%= @proof.abbreviation %>
</p>
<p>
    <strong>Description:</strong>
    <%= @proof.description %>
</p>

<%= link_to 'Edit', edit_proof_path(@proof)%> |
<%= link_to 'Back', proofs_path(@proof) %>